trigger batches on Batch__c (After insert) 
{
  Set<Id> batchIds = new Set<Id>();
  List<Student__c> stuList = new List<Student__c>();
  for(Batch__c batch : Trigger.new){
       Student__c stu = new Student__c();
       stu.Batch__c = batch.id;
       stu.Name = 'Autogenerated record';
       stuList.add(stu);
  }
  insert stuList;
}